# Configuration Render.com pour Rork AI Builder
services:
  - type: web
    name: rork-ai-builder
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm run render:build
    startCommand: npm run render:start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rork-database
          property: connectionString
      - key: NEXT_PUBLIC_APP_URL
        value: https://rork-ai-builder.onrender.com
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRO_PRICE_ID
        sync: false
      - key: STRIPE_ENTERPRISE_PRICE_ID
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: NEXT_PUBLIC_SENTRY_DSN
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

  - type: redis
    name: rork-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru

databases:
  - name: rork-database
    databaseName: rork_ai_builder
    user: rork_user
    plan: starter
    region: oregon